name: creekandmesa
favicon: null
layout_spectrum: 0.25048
typography_spectrum: 0.18472
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Creek and Mesa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#563629'
    - '#a9a8ad'
    - '#997656'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.01686341
purpose: []
