favicon: null
name: creekandmesa
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.6390820387750864
  lightness: 1
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.01686341
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8077571
analytics:
  twitter: null
  google: null
  facebook: null
