analytics: {}
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#563629'
    - '#a9a8ad'
    - '#997656'
  brandStrength: 0
  lightness: 0.8125
  rhythmicContrast: 0.01686341
  saturation: 1
cta: {}
layout_spectrum: 0.412829
name: creekandmesa
opengraph: {}
purpose: []
typography_spectrum: 0.18472
